In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier

In [2]:
dataset = pd.read_csv("health_dataset.csv")
dataset1 = dataset

In [3]:
data1 = pd.get_dummies(dataset1, dtype = int, drop_first = True)
data1

,Glucose_mg_dL,Haemoglobin_g_dL,Cholesterol_mg_dL,Remarks,Full_Name_Abigail Holmes,Full_Name_Alan Floyd,Full_Name_Alan Price,Full_Name_Albert Johnson,Full_Name_Alexandria Wong,Full_Name_Alexis Garcia,...,Email_youngjeremiah@example.com,Email_yramirez@example.org,Email_yrichardson@example.net,Email_yyoung@example.net,Email_zcarr@example.org,Email_zcontreras@example.com,Email_zgray@example.com,Email_zhester@example.net,Email_zlane@example.com,Email_zrodriguez@example.com
0,133,9.5,167,NaN,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,176,10.7,192,NaN,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,193,15.3,303,NaN,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,164,17.2,149,NaN,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,117,13.4,255,NaN,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,72,9.4,207,NaN,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
496,190,10.0,292,NaN,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
497,75,13.8,166,NaN,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
498,156,16.3,319,NaN,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
499,81,11.9,289,NaN,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
dataset1.drop(['Full_Name', 'Date_of_Birth', 'Email', 'Remarks'], axis =1, inplace = True)
dataset1

     Glucose_mg_dL  Haemoglobin_g_dL  Cholesterol_mg_dL
0              133               9.5                167
1              176              10.7                192
2              193              15.3                303
3              164              17.2                149
4              117              13.4                255
..             ...               ...                ...
495             72               9.4                207
496            190              10.0                292
497             75              13.8                166
498            156              16.3                319
499             81              11.9                289

[500 rows x 3 columns]

In [5]:
def assign_disease_risk(row):
    glucose = row["Glucose_mg_dL"]
    haemoglobin = row["Haemoglobin_g_dL"]
    cholesterol = row["Cholesterol_mg_dL"]

    if glucose >= 126 and cholesterol >= 240:
        return "High Health Risk"

    elif glucose >= 126:
        return "Diabetes Risk"
        if random.random() < 0.1:
            disease = "Healthy"

    elif haemoglobin < 12:
        return "Anemia Risk"

    elif cholesterol >= 240:
        return "Heart Disease Risk"
     
    else:
        return "Healthy"

dataset1["Disease_Risk"] = dataset1.apply(assign_disease_risk, axis =1)
dataset1

     Glucose_mg_dL  Haemoglobin_g_dL  Cholesterol_mg_dL        Disease_Risk
0              133               9.5                167       Diabetes Risk
1              176              10.7                192       Diabetes Risk
2              193              15.3                303    High Health Risk
3              164              17.2                149       Diabetes Risk
4              117              13.4                255  Heart Disease Risk
..             ...               ...                ...                 ...
495             72               9.4                207         Anemia Risk
496            190              10.0                292    High Health Risk
497             75              13.8                166             Healthy
498            156              16.3                319    High Health Risk
499             81              11.9                289         Anemia Risk

[500 rows x 4 columns]

In [7]:
X = dataset1.drop("Disease_Risk", axis =1)
Y = dataset1["Disease_Risk"]

x_train, x_test, y_train, y_test = train_test_split(X, Y,test_size = 0.2, random_state = 32)
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [8]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
classifier.fit(x_train,y_train)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [10]:
classifier_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, classifier_pred)
accuracy = accuracy_score(y_test, classifier_pred)
report = classification_report(y_test, classifier_pred)
print(report)

                    precision    recall  f1-score   support

       Anemia Risk       1.00      1.00      1.00        21
     Diabetes Risk       1.00      1.00      1.00        28
           Healthy       1.00      1.00      1.00        16
Heart Disease Risk       1.00      1.00      1.00        10
  High Health Risk       1.00      1.00      1.00        25

          accuracy                           1.00       100
         macro avg       1.00      1.00      1.00       100
      weighted avg       1.00      1.00      1.00       100

In [13]:
import pickle

filename = "health_prediction_model.sav"

pickle.dump(classifier, open(filename, "wb"))
loaded_model = pickle.load(open("health_prediction_model.sav", "rb"))
prediction = loaded_model.predict([[210, 10, 220]])

print(prediction)

['High Health Risk']